#!/usr/bin/env python3
"""Convert tests/interop/captures/*.bin into input/captures.h.

The generated header declares an array of CaptureEntry referencing the
embedded bytes, plus a count. The .ino iterates over it and reports a
PASS/FAIL line per capture.

Filename prefix selects the parser:
  vban_*     → CaptureProtocol::VbanAudio
  vbansvc_*  → CaptureProtocol::VbanService
  rtp_*      → CaptureProtocol::Rtp

Bins whose prefix doesn't match any known protocol are skipped with a
warning so unrelated files (e.g. `README.md`, an editor's swap file)
don't break the build.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path


PROTOCOL_BY_PREFIX = {
    "vban_": "CaptureProtocol::VbanAudio",
    "vbansvc_": "CaptureProtocol::VbanService",
    "rtp_": "CaptureProtocol::Rtp",
}


def classify(stem: str) -> str | None:
    for prefix, proto in PROTOCOL_BY_PREFIX.items():
        if stem.startswith(prefix):
            return proto
    return None


def sanitize_identifier(stem: str) -> str:
    return re.sub(r"[^A-Za-z0-9_]", "_", stem)


def format_bytes(data: bytes) -> str:
    parts = []
    for i in range(0, len(data), 16):
        chunk = data[i : i + 16]
        parts.append("    " + ", ".join(f"0x{b:02X}" for b in chunk) + ",")
    return "\n".join(parts)


def main() -> int:
    here = Path(__file__).resolve().parent.parent
    captures_dir = here / "captures"
    out_path = here / "input" / "captures.h"
    out_path.parent.mkdir(parents=True, exist_ok=True)

    entries = []
    for bin_path in sorted(captures_dir.glob("*.bin")):
        stem = bin_path.stem
        proto = classify(stem)
        if proto is None:
            print(
                f"warning: skipping {bin_path.name} "
                f"(filename prefix not in {sorted(PROTOCOL_BY_PREFIX)})",
                file=sys.stderr,
            )
            continue
        data = bin_path.read_bytes()
        entries.append((stem, proto, data))

    lines = [
        "// Auto-generated by tools/gen_capture_fixtures.py — do not edit.",
        "#ifndef PCMFLOWUDP_INTEROP_CAPTURES_H",
        "#define PCMFLOWUDP_INTEROP_CAPTURES_H",
        "",
        "#include <stdint.h>",
        "#include <stddef.h>",
        "",
        "enum class CaptureProtocol : uint8_t",
        "{",
        "    VbanAudio,",
        "    VbanService,",
        "    Rtp,",
        "};",
        "",
        "struct CaptureEntry",
        "{",
        "    const char *name;",
        "    CaptureProtocol protocol;",
        "    const uint8_t *bytes;",
        "    size_t length;",
        "};",
        "",
    ]

    # Byte arrays
    for stem, _proto, data in entries:
        ident = sanitize_identifier(stem)
        lines.append(f"static const uint8_t kCaptureBytes_{ident}[] = {{")
        if data:
            lines.append(format_bytes(data))
        lines.append("};")
        lines.append("")

    # Registry
    lines.append("static const CaptureEntry kCaptures[] = {")
    for stem, proto, data in entries:
        ident = sanitize_identifier(stem)
        lines.append(
            f'    {{ "{stem}", {proto}, '
            f"kCaptureBytes_{ident}, sizeof(kCaptureBytes_{ident}) }},"
        )
    lines.append("};")
    lines.append("")
    lines.append(
        "static constexpr size_t kCaptureCount = "
        "sizeof(kCaptures) / sizeof(kCaptures[0]);"
    )
    lines.append("")
    lines.append("#endif // PCMFLOWUDP_INTEROP_CAPTURES_H")

    out_path.write_text("\n".join(lines) + "\n")
    print(f"Wrote {out_path} ({len(entries)} captures)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
