/* Auto-generated by tools/bump_version.py - do not edit manually */
#ifndef PCMFLOWUDP_VERSION_H
#define PCMFLOWUDP_VERSION_H

#define PCMFLOWUDP_VERSION_MAJOR 0
#define PCMFLOWUDP_VERSION_MINOR 1
#define PCMFLOWUDP_VERSION_PATCH 0
#define PCMFLOWUDP_VERSION_STR "0.1.0"

#endif // PCMFLOWUDP_VERSION_H
