#ifndef PCMFLOWUDP_RTPPROTOCOL_H
#define PCMFLOWUDP_RTPPROTOCOL_H

#include <stdint.h>
#include <stddef.h>

// PCMFlowUDP :: RTP wire-protocol constants
//
// Constants and a 12-byte fixed-header pack/parse implementation per
// RFC 3550. Static payload-type names follow RFC 3551; Opus is carried
// per RFC 7587 using a caller-chosen dynamic PT (96..127).
//
// PCMFlowUDP emits packets without CSRCs or header extensions
// (V=2, P=0, X=0, CC=0). On receive, packets carrying CSRCs or an
// extension header are parsed correctly: the payload offset is reported
// by `parseRtpHeader` so the caller can locate the payload regardless
// of any padding/extension fields produced by the sender.

namespace pcmflowudp
{
    // Fixed RTP header is exactly 12 bytes (RFC 3550 §5.1). Additional
    // CSRCs (4 bytes each) and an optional header extension may follow;
    // `parseRtpHeader` computes the total via `payloadOffset`.
    static constexpr size_t kRtpHeaderBytes = 12;

    // Conservative payload cap: 1500 (typical Ethernet MTU) - 20 (IP) -
    // 8 (UDP) - 12 (RTP) = 1460. Round down for tags.
    static constexpr size_t kRtpMaxPayloadBytes = 1440;
    static constexpr size_t kRtpMaxPacketBytes =
        kRtpHeaderBytes + kRtpMaxPayloadBytes;

    // RFC 3551 static audio payload-type assignments PCMFlowUDP
    // recognizes by name. Opus is dynamic per RFC 7587 — its PT is
    // chosen by the application (typically 96..127).
    enum class RtpPayloadType : uint8_t
    {
        PCMU = 0,       // G.711 mu-law,  8 kHz mono
        PCMA = 8,       // G.711 A-law,   8 kHz mono
        G722 = 9,       // G.722,         RTP clock 8 kHz (RFC 3551 §4.5.2)
        L16Stereo = 10, // PCM16 BE,     stereo, dynamic clock
        L16Mono = 11,   // PCM16 BE,     mono,   dynamic clock
    };

    // RFC 3550 §5.1 RTP fixed header.
    //
    //  0                   1                   2                   3
    //  0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1
    // +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
    // |V=2|P|X|  CC   |M|     PT      |       sequence number         |
    // +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
    // |                           timestamp                           |
    // +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
    // |                synchronization source (SSRC)                  |
    // +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
    // | (optional CSRCs, header extension — not generated by encode)  |
    //
    // All multi-byte fields are big-endian (network byte order).
    struct RtpHeader
    {
        uint8_t version = 2;         // byte 0 bits 7..6 (always 2 on encode)
        bool padding = false;        // byte 0 bit 5
        bool extension = false;      // byte 0 bit 4
        uint8_t csrcCount = 0;       // byte 0 bits 3..0 (always 0 on encode)
        bool marker = false;         // byte 1 bit 7
        uint8_t payloadType = 0;     // byte 1 bits 6..0
        uint16_t sequenceNumber = 0; // bytes 2..3 (BE)
        uint32_t timestamp = 0;      // bytes 4..7 (BE)
        uint32_t ssrc = 0;           // bytes 8..11 (BE)

        // Computed by parseRtpHeader; ignored by encodeRtpHeader. Tells
        // the caller where the payload begins: kRtpHeaderBytes for a
        // typical PCMFlowUDP-generated packet, more if CSRCs or a
        // header extension are present.
        size_t payloadOffset = kRtpHeaderBytes;
    };

    enum class RtpParseResult : uint8_t
    {
        Ok,
        TooShort,   // input shorter than what the header declares
        BadVersion, // version field is not 2
    };

    // Pack the fixed RTP header (12 bytes) into `out`. Emits V=2, P=0,
    // X=0, CC=0 regardless of the corresponding fields in `in` (PCMFlowUDP
    // does not generate padding, extension, or contributing-source
    // packets). Returns false on null `out` or payloadType > 0x7F.
    bool encodeRtpHeader(const RtpHeader &in, uint8_t *out);

    // Parse the leading RTP header of `in`. Handles CSRCs and a (skipped)
    // header extension transparently — the relevant fields are filled
    // and `out.payloadOffset` points at the first payload byte. Returns
    // TooShort if `len` is shorter than the declared header (incl.
    // CSRCs / extension), BadVersion if V != 2.
    RtpParseResult parseRtpHeader(const uint8_t *in,
                                  size_t len,
                                  RtpHeader &out);
} // namespace pcmflowudp

#endif // PCMFLOWUDP_RTPPROTOCOL_H
