// Interop test: run each captured wire-format packet through the
// matching parser and report PASS / FAIL per entry. Captures live as
// auto-generated byte arrays in input/captures.h (built from
// captures/*.bin by tools/gen_capture_fixtures.py before each pytest
// run).
//
// If captures/ is empty the array is empty and this sketch reports
// `INTEROP captures=0`; the pytest side skips with a hint pointing
// at captures/README.md.

#include <PCMFlowUDP.h>
#include "input/captures.h"

static int g_pass = 0;
static int g_total = 0;

static void runOne(const CaptureEntry &e)
{
    ++g_total;
    bool ok = false;

    switch (e.protocol)
    {
    case CaptureProtocol::VbanAudio:
    {
        pcmflowudp::VbanAudioHeader h{};
        ok = (pcmflowudp::parseAudioHeader(e.bytes, e.length, h) ==
              pcmflowudp::VbanParseResult::Ok);
        if (ok)
        {
            Serial.print("CAP ");
            Serial.print(e.name);
            Serial.print(" rate=");
            Serial.print(pcmflowudp::vbanSampleRateHz(h.sampleRateIndex));
            Serial.print(" ch=");
            Serial.print(h.numChannels);
            Serial.print(" samples=");
            Serial.println(h.numSamples);
        }
        break;
    }
    case CaptureProtocol::VbanService:
    {
        pcmflowudp::VbanServiceHeader h{};
        ok = (pcmflowudp::parseServiceHeader(e.bytes, e.length, h) ==
              pcmflowudp::VbanParseResult::Ok);
        if (ok)
        {
            Serial.print("CAP ");
            Serial.print(e.name);
            Serial.print(" func=");
            Serial.print(h.serviceFunction);
            Serial.print(" flags=0x");
            Serial.println(h.serviceFlags, HEX);
        }
        break;
    }
    case CaptureProtocol::Rtp:
    {
        pcmflowudp::RtpHeader h{};
        ok = (pcmflowudp::parseRtpHeader(e.bytes, e.length, h) ==
              pcmflowudp::RtpParseResult::Ok);
        if (ok)
        {
            Serial.print("CAP ");
            Serial.print(e.name);
            Serial.print(" pt=");
            Serial.print(h.payloadType);
            Serial.print(" seq=");
            Serial.print(h.sequenceNumber);
            Serial.print(" payloadOff=");
            Serial.println(h.payloadOffset);
        }
        break;
    }
    }

    if (ok)
    {
        ++g_pass;
        Serial.print("PASS ");
        Serial.println(e.name);
    }
    else
    {
        Serial.print("FAIL ");
        Serial.println(e.name);
    }
}

void setup()
{
    Serial.begin(115200);
    delay(5000); // ESP32 Serial-USB bridge can drop early output otherwise

    Serial.print("INTEROP captures=");
    Serial.println(kCaptureCount);

    for (size_t i = 0; i < kCaptureCount; ++i)
        runOne(kCaptures[i]);

    Serial.print("TEST done ");
    Serial.print(g_pass);
    Serial.print("/");
    Serial.println(g_total);
}

void loop()
{
    delay(1);
}
